Incremental builds.  Fix #194.
mozilla/sphinx-js pull request #195
Opened 2022-04-22 20:48 UTC by ncalexan

2022-04-22 21:00 UTC, ncalexan commented
@erikrose oh hai!  Are you willing to review?  I can probably arrange for somebody within Mozilla to review if you're not available.

2022-05-01 04:54 UTC, lonnen requested changes

2022-05-01 04:54 UTC, lonnen commented on sphinx_js/typedoc.py
> +        while True:
This has some code duplication with `_containing_module()`. Maybe that can be extracted to an iterator that `_containing_module()` and `_containing_deppath()` can use

2022-05-01 05:00 UTC, lonnen commented
@ncalexan Hello and thanks for the PR. This looks like a very useful feature! I took a pass and had two suggestions

2022-05-10 00:39 UTC, lonnen commented on sphinx_js/renderers.py
> +    def get_object(self):
`get_object()` is used by this name with this signature in both the jsdoc and typedoc modules in addition to this Analyzer class. They're not descendants of one another but that's enough examples for me to change my mind on this.

retracted

2022-05-10 17:41 UTC, lonnen commented
I took this branch and added my own review requests in hopes of getting this landed faster. see also: https://github.com/mozilla/sphinx-js/pull/197

2022-05-13 22:34 UTC, lonnen approved these changes

2022-05-13 22:34 UTC, lonnen commented
Merged #197

2022-05-13 22:34 UTC, closed without merging